server {
    listen 80;

    location /api/auth/ {
        proxy_pass http://auth:8082/;
        proxy_set_header Host $host;
    }

    location /api/matchmaker/ {
        proxy_pass http://matchmaker:8083/;
        proxy_set_header Host $host;
    }

    location /ws {
        proxy_pass http://game:8081/ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri /index.html;
    }
}
